### PR TITLE
added stubbed out methods for the api

### PR DESCRIPTION
**Pull request by megazear7**

### CODE REVIEW

**Comment by NSMarkop** [comment]
I should set up a local db but I'm lazy so I've just been using the actual server so I don't have to re-input what I'm testing...

As for user creation, that will be part of the receiving message function, right? If there is a null given id or something like that. However, since we're currently having the id for users assigned automatically, I'm not sure how to get that id back to be able to return it to the user. Maybe something using this?

http://docs.sqlalchemy.org/en/rel_0_7/core/connections.html?highlight=inserted_primary_key#sqlalchemy.engine.base.ResultProxy.inserted_primary_key

Or, we create another function that generates a random 64-bit integer and modify user to take an integer in its initialization function. If we're generating it randomly, there's always the small chance that that id already exists in the user table so we'd have to check whether or not the insert into the User table failed and re-generate a number to try again if so.

So do you want to do messages or zones? Should we make the actual functions in other files (zone_api, messages_api) that the stubbed functions call to avoid any potential merging issues with us working in the same file?

**Comment by megazear7** [comment]
How are you inputing enum's?

**Comment by NSMarkop** [comment]
I typed up a response on my phone earlier but it doesn't seem to have gone through... Github on mobile sucks.

How am I inputting enums into what? You just make the object with the value. I haven't checked if it actually throws an error or whatever when you try giving it a value that isn't part of the established enum, though.

1. Ah, right, my bad. We probably want to just have another function in our api for user ID checking / generation that is called whenever the app is opened. So it'd check if the given user id is in the db and if it is just return it and if it's not then generate a random one, put it in the db, and return it. That's not really a GET since it potentially modifies stuff, though.

2. We could put that inside the internals of User init or we could just pass it the randomly generated id, set self.id to that id, and check if the transaction of adding that to the db worked. I just figured we'd do it the latter way so that whatever outside function is creating that User instance will have access to the id to be able to return it in the response to the client after it successfully adds one.

3. Okie dokie. I'll do the two zone ones then. I won't be home until later tonight but it shouldn't take long to implement them on a basic level.

4. Alright. I tend to like working in different files so I'll probably do that and then we can merge them or do whatever whenever like you said.

**Comment by megazear7** [comment]
I am doing this
```python
user = User("admin", datetime.datetime.now(), datetime.datetime.now())
session.add(user)
session.commit()
```
But it is giving an error because evidently your not supposed to pass strings for the enum. So is there something like Enum.admin that I am supposed to pass instead?

1. Yeah it should be a post. And the client only needs to do it the first time the start the app and then they can store it on the device.

2. I am up for that. At some point we should change it from an integer to a varchar with like 32 characters or something so that there can be lots and lots of values and people can't guess values. We can go with an integer for now though

3. nothing to add.

4. Whenever you get on tonight go ahead and split them into files and get the hookups from app.py to make it all work and commit that to this branch. I'll have all my changes up by then so I can just pull your changes down whenever I work on it again. Remember to update your local branch with my changes and then modify things on top of that.

**Comment by NSMarkop** [comment]
Looking at our currently defined User in models, the enum only accepts 'default' and 'banned'. That might be the issue. I can't recall having problems when adding test zones earlier.

1. So are we going to keep track of if it's the user's first time starting the app then? Not us on the server, but the client-side would have to then in order to make an api call to our user generation function. That would clear up the ambiguity I had with the checking + generation being combined though, so that'd be good.

2. Good idea.

3. I too having nothing to add.

4. Yep, will do. Hopefully I don't mess everything up as sometimes happens when I use branches and merging and all that on github :P

**Comment by megazear7** [comment]
1. When the app starts up it would check /path/to/file/storing/this/devices/id. If it wasn't there then it would ask the server for a new user_id.

4. It will all be good I am sure haha

**Comment by megazear7** [comment]
You were correct about the "admin" thing. I added admin after I created the database for the first time so postgres rejected it. So how do we add values to the Enum? do we have to do it manually through postgres?

**Comment by NSMarkop** [comment]
Well for the Enums they are something that really should be set and then not changed on the fly, so having to edit them into models.py and pushing that change isn't bad in my opinion. As long as you don't remove any Enums then you wouldn't even need to reset any of the data in the tables doing that. However I'm sure there's a way to add more value types to the Enum (we even give them names after all), but I'm not sure how as I've never tried.

**Comment by megazear7** [comment]
Editing the Enums in models.py doesn't actually change anything though, even when you restart the server. I think you pretty much have to interact directly with the database and then change models.py to reflect it.

**Comment by megazear7** [comment]
I am getting 500 errors for zone creation. Also I have tried numerous things to get an error log working but still can't get a helpful error log. Lastly both my methods are returning 500 errors and I can't figure out why. Ugh this has been really stressful over the last few days, everything I try just doesn't work lol. Learning python and learning flask has been tough. Anyway I will stay on it and keep it going but will need to take a break to do the presentation and other homework.

**Comment by NSMarkop** [comment]
Ah, yeah, you're right about the Enum thing - I always forget there's actual DB code that isn't as interactive as the Python bits :P My first thought then (without editing the db directly) is to make the change in models.py, drop all of your tables using db.drop_all() (or just drop the one table you want to change), and then recreate using the db.create_all() function. I also found this link real quick which suggests the same idea and warns about the enum value not being deleted (might not be true anymore, haven't tried this):

https://groups.google.com/forum/#!topic/sqlalchemy/HqI3OizHBG4

What I have found thus far for doing this without that kind of data loss is that you need to perform database migration, something that sqlalchemy doesn't do, in order to alter tables after creation. That would mean we could use sqlalchemy-migrate ( https://sqlalchemy-migrate.readthedocs.org/en/latest/ ) or Alembic ( https://alembic.readthedocs.org/en/latest/ ). 

Alembic seems to be made by the same person as sqlalchemy and so is kind of more official I guess (it's even linked to from the sqlalchemy site). Alternatively, we could just alter it manually in the Postgres db (don't even need to change models.py but we would want to document the changes by doing so in case we have to rebuild the db at some point). The latter is easier but the former is better I think so we should start looking into that at some point after we have all this basic stuff nailed down.

**Comment by NSMarkop** [comment]
Zone creation has worked fine for me on my local db as well as on the heroku one. For reference, I used curl like this:

curl -i -H "Content-Type: application/json" -X POST -d '{"name":"testing","description":"this is a test description","type":"bar","latitude_1":1,"longitude_1":1,"latitude_2":2,"longitude_2":2,"latitude_3":3,"longitude_3":3,"latitude_4":4,"longitude_4":4}' http://localhost:5000/zone

Though I obviously changed localhost to chatzone.herokuapp.com when testing on the actual server.

In terms of error logs, I'm not sure. I was having lots of 500 issues and such with mine when writing them but I'm kind of a print debugger so I commented out all the lines of code and made the return something like return 'testing'. Then if that worked I uncommented one line and ran it again, continuing this until I started getting 500 errors so I knew where it came from. Mine were mostly from using request incorrectly (which I still need to clean up some code from that point as I left request.json stuff in my checking code on accident).

It's okay, don't stress too much! We can talk problems through and figure out how to make things work, plus we have plenty of time to get stuff working. I'll try looking at your code later to see what might be causing the 500 errors as I am also getting them when trying to run them.

**Comment by megazear7** [comment]
1. Lets prioritize database migrations as it will be a good tool to have available especially after we get some real data in the database it would be nice to keep without having to export all of the data and then re-import. But for now if an urgent need arises we can manually alter the database. 

2. I will go ahead and start using print statements. Does it go directly to the server output?

3. I will use that curl command and see what happens haha.

**Comment by NSMarkop** [comment]
1. Yeah, I agree. Alternatively, since what we want is so trivial, we could use SQLAlchemy to execute the SQL for us using this:

http://docs.sqlalchemy.org/en/rel_0_8/orm/session.html#sqlalchemy.orm.session.Session.execute

That way we could automate the creation of a log of the alterations we make when executing the SQL which would mean we wouldn't need to modify models.py. If we needed to recreate the db we could just do db.create_all() then call our alter function in a loop to execute all of the alterations in our log file.

Just throwing out some thoughts as setting up for using a migration library is a lot more work, though more useful/practical in general for sure haha.

2. You don't use actual print statements, I just meant the same methodology as print debugging. You're technically using the return as your print in the example I gave so that you can actually see if it got to that point in the code as you can't see the output of print statements as far as I know.

**Comment by megazear7** [comment]
Ah okay. I am going to go ahead and merge this into master. I don't want it hanging around any longer haha.

**Pull request merged**
